# Generated by Django 3.0.7 on 2022-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20221004_0625'),
        ('store', '0006_auto_20221007_1112'),
    ]

    operations = [
    ]
